# Generated by Django 5.0.1 on 2024-01-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendency',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendency',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
