# Generated by Django 5.0.1 on 2024-01-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit2', '0002_physicalorphan_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='filename',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
