# Generated by Django 5.0.1 on 2024-01-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit2', '0005_alter_searchhistory_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
