# Generated by Django 5.0.1 on 2024-01-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit2', '0006_alter_searchhistory_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='filename',
        ),
    ]
