# Generated by Django 5.0.1 on 2024-01-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit2', '0007_remove_searchhistory_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
