# Generated by Django 5.0.1 on 2024-01-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit2', '0008_searchhistory_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='uuid',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
